name: product_tiers
columns:
    - { name: "id", type: "integer", key: true, nullable: false, autoincrement: true }
    - { name: "name", type: "string" }
    - { name: "description", type: "text" }
    - { name: "permissions", type: "text" }
    - { name: "deleted_at", type: "datetime" }
    - { name: "updated_at", type: "datetime" }