name: profiles
columns:
    - { name: "id", type: "integer", key: true, nullable: false, autoincrement: true }
    - { name: "business_id", type: "integer", nullable: false }
    - { name: "created_at", type: "datetime" }
    - { name: "updated_at", type: "datetime" }
    - { name: "deleted_at", type: "datetime" }