##############################################################################
# Settings file for project
##############################################################################
# When the --env=test string is passed in, it will use the database settings
#   specified in the "test" portion of the file. You can pass any environment
#   string as long as there is a corresponding entry here or ".project.yaml" 
#   file.  The ".jake" file should contain settings that should NOT 
#   be checked into a version control system.  Typically, they should contain
#   things like the production database credentials.

settings:
    # The name of the changelog table that is used to track versions
    migration_table: migrations
    
    # The number of spaces to indent in the yaml files, default is 4.
    indent: 4
    
    # This is the default environment to use if none is specified
    # This should probably go in the ".jake" file
    environment: dev

environments:
    # The name of the environment
    dev:
        vendor: mysql  # postgres, mssql
        host: localhost
        database: test
        user: root
        password: j@s0n_example3